<?php

namespace webworks\CSVBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class webworksCSVBundle extends Bundle
{

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
